version: '3.1'

services:     
                
    virtuoso:
        image: tenforce/virtuoso
        environment:
            SPARQL_UPDATE: "true"
            DEFAULT_GRAPH: "http://envri-data"
        volumes:
            - virtuoso-data:/data/virtuoso
        ports:
            - "8890:8890"
            - "1111:1111"
            
    #mongo:
        #image: mongo
        #volumes:
            #- mongo-data:/data/db
        #ports:
            #- "27017:27017"     
            
    #zookeeper:
        #image: zookeeper      
        #ports:
        #- "2181:2181"

        
    #activemq:
        #image: rmohr/activemq 
        #ports:
        #- "61616:61616"
        #- "8161:8161"
        

            
    vreportal:
        image: vre_portal
        environment:
            SPRING_DATASOURCE_URL: "jdbc:h2:~/evre;DB_CLOSE_ON_EXIT=FALSE"
            H2MANAGER_DATASOURCE_URL: "jdbc:h2:~/evre"
            SPRING_DATASOURCE_USERNAME: "sa"
            SPRING_DATASOURCE_PASSWORD: ""
            SPRING_HTTP_MULTIPART_MAX_FILE_SIZE: "400Mb"
            SPRING_HTTP_MULTIPART_MAX_REQUEST_SIZE: "400Mb"
            SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.h2.Driver"
            TRIPLESORE_NAMESPACE: "vre4eic"
            SERVICE_URL: "http://metadata:8080/EVREMetadataServices"
            SERVICE_TIMEOUT: "6"
            SERVICE_MAX_RESULT_COUNT: "10000"
            URI_PREFIX: "http://vreportal"
            PORTAL_STATE: "public"
        ports:
            - "80:8080"
        depends_on:
            - metadata
            
    metadata:
        image: evre_metadata_service
        environment:
            VIRTUOSO_URL: "virtuoso"
            VIRTUOSO_USERNAME: "dba"
            VIRTUOSO_PASSWORD: "dba"
            VIRTUOSO_PORT: "1111"
            VIRTUOSO_REST_URL: "http://virtuoso:8890"
            #VIRTUOSO_REST_URL: "http://v4e-hub.isti.cnr.it:8890"
            METADATA_ENDPOINT: "http://metadata:8080/EVREMetadataServices"
            WORKFLOWS_GRAPH: "http://vre/workflows"
            WORKFLOWS_GRAPH_LABEL: "Workflows"
            NODELINK_URL: "v4e-lab.isti.cnr.it:2181"
            NODELINK_ENDPOINT: "http://v4e-lab.isti.cnr.it:8080/NodeService"
            #NODELINK_ENDPOINT: "http://node_service:8080/NodeService"
        ports:
            - "8080:8080"   
        depends_on:
            - virtuoso


    #node_service:
        #image: node_service
        #environment:
            #EVRE_SETTINGS_VERSION: "0.3"
            #EVRE_SETTINGS_AUTHENTICATION_TOKEN_TIMEOUT: "60"
            #EVRE_SETTINGS_AUTHENTICATION_CODE_TIMEOUT: "60"
            #EVRE_SERVICES_MESSAGE_BROKER: "tcp://activemq:61616"
            #EVRE_SERVICES_PROFILE_STORAGE_URL: "mongo"
            #EVRE_SERVICES_PROFILE_STORAGE_PORT: "27017"
            #ADMIN_USER: "administrator@fakeemail.com"
            #ADMIN_PASSWORD: "johnjohn78"
            #VERSION: "0.0.3"
            #LICENSE_TYPE: "TBD"
            #LICENSE_URL: "licensedoc"
            #NOTIFICATION_API_KEY: "aaaaaaaaaaaaa"
            #ZOOKEEPER_DEFAULT: "zookeeper:2281"
            #TOKEN_SECRET_DEFAULT: "fvsecret"
            #AAAI_LOGIN_DEFAULT: "admin"
            #AAAI_PWD_DEFAULT: "admin"
            #AAAI_LOGIN: "admin"
        #ports:
            #- "8081:8080"           
            
    

volumes:
  virtuoso-data:
  h2-data:
  #mongo-data:
