version: '3.1'

services:     
                
    rabbit:
        image: rabbitmq:3-management
        deploy:
            restart_policy:
                condition: on-failure      
                                
    rest-cat:
        image: rest-cat
        deploy:
            restart_policy:
                condition: on-failure
        environment:
            RABBIT_HOST: rabbit
            RABBIT_PORT: 5672
            RABBIT_USERNAME: guest
            RABBIT_PASSWORD: guest
            INFLUX_URI: http://influx:8086
            WEBDAV_HOST: webdav            
        ports:
            - 8083:8080      
        depends_on:
            - rabbit          
            - influx          
            
    cat-worker:
        image: cat-worker
        deploy:
            restart_policy:
                condition: on-failure
            replicas: 2
        environment:
            RABBIT_HOST: rabbit
            RABBIT_PORT: 5672
            RABBIT_USERNAME: guest
            RABBIT_PASSWORD: guest
            INFLUX_URI: http://influx:8086
            WEBDAV_HOST: webdav
            WEBDAV_USERNAME: user
            WEBDAV_PASSWORD: resu      
        depends_on:
            - rabbit   
            - webdav
            
    prise:
        image: prise
        environment:
            RABBIT_HOST: "rabbit"
            RABBIT_PORT: "5672"
            RABBIT_USERNAME: "guest"
            RABBIT_PASSWORD: "guest"
            INFLUX_URI: "http://influx:8086"
            WF_REPO_URL: "http://webdav/"
            PROV_REPO_URL: "http://webdav/"
            LOG_REPO_URL: "http://webdav/"
        ports:
            - "8084:8080"
            
            
    #pylog2prov:
        #image: pylog2prov
        #environment:
            #RABBIT_HOST: "rabbit"
            #RABBIT_PORT: "5672"
            #RABBIT_USERNAME: "guest"
            #RABBIT_PASSWORD: "guest"
             
    #statistics-cat:
        #image: statistics-cat
        #deploy:
            #restart_policy:
                #condition: on-failure                
        #environment:
            #WEBDAV_HOST: webdav
            #WEBDAV_USERNAME: user
            #WEBDAV_PASSWORD: resu    
            #RABBIT_HOST: rabbit
            #QUEUE_NAME: rdf_location
        #depends_on:
            #- webdav              

    webdav:
        image: visity/webdav
        ports:
            - 80:80
        deploy:
            restart_policy:
                condition: on-failure       
        volumes:
            - webdav:/var/www             
            
    #jena-fuseki: 
        #image: stain/jena-fuseki
        #ports:
            #- 3030:3030 
        #deploy:
            #restart_policy:
                #condition: on-failure  
        #environment:
            #ADMIN_PASSWORD: "admin"
        #volumes:
            #- fuseki-data:/fuseki           
            
    influx:
        image: influxdb
        environment:
            INFLUXDB_DB: mydb
        volumes:
            - influx:/var/lib/influxdb
                    
    #rabbit-reporter :
        #image: alogo53/rabbit-metrics-reporter
        #environment:
            #RABBIT_HOST: rabbit
            #RABBIT_PORT: 15672
            #RABBIT_USERNAME: guest
            #RABBIT_PASSWORD: guest
            #INFLUX_HOST: influx
            #INFLUX_PORT: 8086
            #INFLUX_DB: mydb
            #REPORT_INTERVAL: 10
        #depends_on:
            #- rabbit
            #- influx
            
    grafana:
        image: grafana/grafana
        environment:
            DS_NAME: InfluxDB
            DS_TYPE: InfluxDB
            DS_ACCESS: proxy
            DS_URL: http://influx:8086
            DS_DB: cadvisor
        ports:
            - 3000:3000
        volumes:
            - grafana:/var/lib/grafana
        depends_on:
            - influx
        deploy:
            replicas: 1
        depends_on:
            - influx    
            
    #chronograf:
        #image: chronograf
        #ports:
            #- 8888:8888
        #command: chronograf --influxdb-url=http://influx:8086
        #depends_on:
            #- influx

    #kapacitor:
        #image: kapacitor
        #environment:
            #KAPACITOR_HOSTNAME: kapacitor
            #KAPACITOR_INFLUXDB_0_URLS_0: http://influxdb:8086
        #volumes:
            #- ./data/kapacitor:/var/lib/kapacitor
        #depends_on:
            #- influx
        #ports:
            #- 9092:9092
      
                    
    cadvisor:
        image: google/cadvisor
        #ports:
            #- 0.0.0.0:8080:8080
        hostname: '{{.Node.ID}}'
        command: -logtostderr -docker_only -storage_driver=influxdb -storage_driver_db=mydb -storage_driver_host=influx:8086
        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:rw
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro
        depends_on:
            - influx
        deploy:
            mode: global           
              
            
                                
volumes:
  influx:
  grafana:
  webdav:
  fuseki-data:
    
