apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: influx
  name: influx
spec:
  replicas: 1
  selector:
   matchLabels:
    app: influx  
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: influx
    spec:
      containers:
      - env:
        - name: INFLUXDB_DB
          value: mydb
        image: influxdb
        name: influx
        ports:
        - containerPort: 8086
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/influxdb
          name: influx
      restartPolicy: Always
      volumes:
      - name: influx
        persistentVolumeClaim:
          claimName: influx
status: {}
